set( APPLICATION_NAME       "MagentaCLOUD" )
set( APPLICATION_SHORTNAME  "MagentaCLOUD" )
set( APPLICATION_EXECUTABLE "magentacloud" )
set( APPLICATION_CONFIG_NAME "magentacloud" )
set( LINUX_APPLICATION_ID "com.t_systems.android.webdav.magentacloud" )
set( APPLICATION_DOMAIN     "pre1.next.magentacloud.de" )
set( APPLICATION_VENDOR     "Nextcloud GmbH" )
set( APPLICATION_UPDATE_URL "https://customerupdates.nextcloud.com/client/" CACHE string "URL for updater" )
set( APPLICATION_HELP_URL   "https://cloud.telekom-dienste.de/hilfe" CACHE string "URL for the help menu" )
set( APPLICATION_ICON_NAME "Nextcloud" )
set( APPLICATION_ICON_SET  "SVG" )
set( APPLICATION_SERVER_URL "https://pre1.next.magentacloud.de" CACHE string "URL for the server to use. If entered the server can only connect to this instance" )
set( APPLICATION_SERVER_URL_ENFORCE ON )
set( DO_NOT_USE_PROXY OFF )
set( LINUX_PACKAGE_SHORTNAME "magentacloud" )
set( THEME_CLASS            "NextcloudTheme" )
set( APPLICATION_REV_DOMAIN "com.t_systems.android.webdav" )
set( WIN_SETUP_BITMAP_PATH  "${CMAKE_SOURCE_DIR}/admin/win/nsi" )
set( MAC_INSTALLER_BACKGROUND_FILE "${CMAKE_SOURCE_DIR}/admin/osx/installer-background.png" CACHE STRING "The MacOSX installer background image")
option( WITH_CRASHREPORTER "Build crashreporter" OFF )
option( WITH_PROVIDERS "Build with providers list" OFF )
option( BUILD_UPDATER "Build with updater" ON )
set( NEXTCLOUD_BACKGROUND_COLOR "#E20074" CACHE string "Hex color of the wizard header background")
set( APPLICATION_WIZARD_HEADER_BACKGROUND_COLOR "#E20074" CACHE string "Hex color of the wizard header background")
set( APPLICATION_WIZARD_HEADER_TITLE_COLOR "#ffffff" CACHE string "Hex color of the text in the wizard header")
option( APPLICATION_WIZARD_USE_CUSTOM_LOGO "Use the logo from ':/client/theme/colored/wizard_logo.png' else the default application icon is used" ON )
set(ENCRYPTION_HARDWARE_TOKEN_DRIVER_PATH {})
set (CLIENTSIDEENCRYPTION_ENFORCE_USB_TOKEN false)
option(ENFORCE_SINGLE_ACCOUNT "Enforce use of a single account in desktop client" ON)
