SET(CMAKE_SYSTEM_NAME Windows)
SET(MINGW_PREFIX  /usr/bin/x86_64-w64-mingw32)


# specify the cross compiler
SET(CMAKE_C_COMPILER ${MINGW_PREFIX}-gcc)
SET(CMAKE_CXX_COMPILER ${MINGW_PREFIX}-g++)
SET(CMAKE_RC_COMPILER ${MINGW_PREFIX}-windres)

# where is the target environment containing libraries
SET(CMAKE_FIND_ROOT_PATH  ${MINGW_PREFIX})
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM  NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY  ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE  ONLY)
