name: Linux GCC compilation and tests
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Linux GCC compilation and tests
    runs-on: ubuntu-22.04
    container: ghcr.io/nextcloud/continuous-integration-client:client-5.15-14
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Configure and compile
        run: |
          mkdir build
          cd build
          cmake .. -G Ninja -DCMAKE_C_COMPILER=gcc-11 -DCMAKE_CXX_COMPILER=g++-11 -DCMAKE_BUILD_TYPE=Debug -DQUICK_COMPILER=ON -DBUILD_UPDATER=ON -DBUILD_TESTING=1 -DECM_ENABLE_SANITIZERS=address -DCMAKE_CXX_FLAGS=-Werror -DOPENSSL_ROOT_DIR=/usr/local/lib64
          ninja
      - name: Run tests
        run: |
          cd build
          useradd -m -s /bin/bash test
          chown -R test:test .
          su -c 'ASAN_OPTIONS=detect_odr_violation=0,detect_leaks=0 xvfb-run ctest --output-on-failure' test
